DROP TABLE IF EXISTS contactos;

CREATE TABLE Contactos (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nb VARCHAR(30) NOT NULL UNIQUE,
phone INT UNIQUE,
home VARCHAR(50),
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CHECK (phone>99999999 and phone<1000000000)
);